.TH "src/src/main.c" 3 "Fri Feb 26 2021" "Version 1.0" "Lista Enlazada" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lista\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv, char const **envp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv, char const ** envp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lista Enlazada from the source code\&.
