.TH "node" 3 "Fri Feb 26 2021" "Version 1.0" "Lista Enlazada" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lista\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdata\fP"
.br
.RI "data "
.ti -1c
.RI "struct \fBnode\fP * \fBnext\fP"
.br
.RI "pointer to next element "
.in -1c
.SH "Field Documentation"
.PP 
.SS "int data"

.PP
data 
.SS "struct \fBnode\fP* next"

.PP
pointer to next element 

.SH "Author"
.PP 
Generated automatically by Doxygen for Lista Enlazada from the source code\&.
